import { Account, Transaction, SetupProgress, WatchlistItem } from '@/types/database';

const USER_ID = 'demo-user-001';

function daysAgo(days: number, hours = 12, minutes = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

export const seedAccounts: Account[] = [
  {
    id: 'acc-gbp-001',
    user_id: USER_ID,
    currency: 'GBP',
    balance: 125000,
    is_primary: true,
    account_number: '12345678',
    sort_code: '04-00-75',
    iban: 'GB29 REVO 0400 7512 3456 78',
    created_at: daysAgo(90),
    updated_at: daysAgo(0),
  },
  {
    id: 'acc-eur-001',
    user_id: USER_ID,
    currency: 'EUR',
    balance: 50000,
    is_primary: false,
    account_number: null,
    sort_code: null,
    iban: 'LT60 3250 0000 0000 0001',
    created_at: daysAgo(60),
    updated_at: daysAgo(1),
  },
  {
    id: 'acc-usd-001',
    user_id: USER_ID,
    currency: 'USD',
    balance: 20000,
    is_primary: false,
    account_number: null,
    sort_code: null,
    iban: null,
    created_at: daysAgo(30),
    updated_at: daysAgo(2),
  },
];

export const seedTransactions: Transaction[] = [
  // Today
  {
    id: 'txn-001',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -850,
    currency: 'GBP',
    description: 'Grab ride',
    category: 'Transport',
    merchant_name: 'Grab',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(0, 9, 15),
  },
  {
    id: 'txn-002',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -420,
    currency: 'GBP',
    description: 'Starbucks coffee',
    category: 'Food & Drink',
    merchant_name: 'Starbucks',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(0, 8, 30),
  },
  // Yesterday
  {
    id: 'txn-003',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -3280,
    currency: 'GBP',
    description: 'Weekly groceries',
    category: 'Shopping',
    merchant_name: 'Tesco',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(1, 18, 45),
  },
  {
    id: 'txn-004',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -280,
    currency: 'GBP',
    description: 'Tube fare',
    category: 'Transport',
    merchant_name: 'TfL',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(1, 8, 10),
  },
  // 2 days ago
  {
    id: 'txn-005',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -1599,
    currency: 'GBP',
    description: 'Monthly subscription',
    category: 'Entertainment',
    merchant_name: 'Netflix',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(2, 3, 0),
  },
  {
    id: 'txn-006',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -2499,
    currency: 'GBP',
    description: 'Online order',
    category: 'Shopping',
    merchant_name: 'Amazon',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(2, 14, 20),
  },
  // 3 days ago
  {
    id: 'txn-007',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'deposit',
    amount: 350000,
    currency: 'GBP',
    description: 'Monthly salary',
    category: 'Income',
    merchant_name: 'Acme Corp',
    merchant_logo: null,
    status: 'completed',
    reference: 'SAL-2026-03',
    recipient_id: null,
    created_at: daysAgo(3, 9, 0),
  },
  {
    id: 'txn-008',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -750,
    currency: 'GBP',
    description: 'Lunch',
    category: 'Food & Drink',
    merchant_name: 'Pret A Manger',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(3, 12, 30),
  },
  // 4 days ago
  {
    id: 'txn-009',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'transfer',
    amount: -5000,
    currency: 'GBP',
    description: 'Transfer to Alex',
    category: 'Transfers',
    merchant_name: null,
    merchant_logo: null,
    status: 'completed',
    reference: 'P2P-001',
    recipient_id: 'user-alex-001',
    created_at: daysAgo(4, 16, 0),
  },
  {
    id: 'txn-010',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -1200,
    currency: 'GBP',
    description: 'Uber ride',
    category: 'Transport',
    merchant_name: 'Uber',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(4, 22, 15),
  },
  // 5 days ago
  {
    id: 'txn-011',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -3500,
    currency: 'GBP',
    description: 'Dinner',
    category: 'Food & Drink',
    merchant_name: 'Wagamama',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(5, 19, 45),
  },
  {
    id: 'txn-012',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -999,
    currency: 'GBP',
    description: 'Spotify Premium',
    category: 'Entertainment',
    merchant_name: 'Spotify',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(5, 4, 0),
  },
  // 6 days ago
  {
    id: 'txn-013',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -4599,
    currency: 'GBP',
    description: 'Sainsburys groceries',
    category: 'Shopping',
    merchant_name: "Sainsbury's",
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(6, 17, 0),
  },
  // 7 days ago
  {
    id: 'txn-014',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -280,
    currency: 'GBP',
    description: 'Bus fare',
    category: 'Transport',
    merchant_name: 'TfL',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(7, 7, 50),
  },
  {
    id: 'txn-015',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'transfer',
    amount: 2500,
    currency: 'GBP',
    description: 'From Sarah',
    category: 'Transfers',
    merchant_name: null,
    merchant_logo: null,
    status: 'completed',
    reference: 'P2P-002',
    recipient_id: null,
    created_at: daysAgo(7, 14, 30),
  },
  // 8 days ago
  {
    id: 'txn-016',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -8900,
    currency: 'GBP',
    description: 'Nike trainers',
    category: 'Shopping',
    merchant_name: 'Nike',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(8, 11, 0),
  },
  // 10 days ago
  {
    id: 'txn-017',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -650,
    currency: 'GBP',
    description: 'Costa Coffee',
    category: 'Food & Drink',
    merchant_name: 'Costa',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(10, 10, 15),
  },
  {
    id: 'txn-018',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -1499,
    currency: 'GBP',
    description: 'Cinema tickets',
    category: 'Entertainment',
    merchant_name: 'Odeon',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(10, 20, 0),
  },
  // 12 days ago
  {
    id: 'txn-019',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'exchange',
    amount: -10000,
    currency: 'GBP',
    description: 'Exchange GBP to EUR',
    category: 'Exchange',
    merchant_name: null,
    merchant_logo: null,
    status: 'completed',
    reference: 'EX-001',
    recipient_id: null,
    created_at: daysAgo(12, 15, 0),
  },
  {
    id: 'txn-020',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -350,
    currency: 'GBP',
    description: 'Newspaper',
    category: 'Shopping',
    merchant_name: 'WHSmith',
    merchant_logo: null,
    status: 'completed',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(12, 8, 0),
  },
  // Pending transaction
  {
    id: 'txn-021',
    user_id: USER_ID,
    account_id: 'acc-gbp-001',
    type: 'payment',
    amount: -1999,
    currency: 'GBP',
    description: 'Deliveroo order',
    category: 'Food & Drink',
    merchant_name: 'Deliveroo',
    merchant_logo: null,
    status: 'pending',
    reference: null,
    recipient_id: null,
    created_at: daysAgo(0, 11, 30),
  },
  // EUR transactions
  {
    id: 'txn-022',
    user_id: USER_ID,
    account_id: 'acc-eur-001',
    type: 'deposit',
    amount: 50000,
    currency: 'EUR',
    description: 'Exchange from GBP',
    category: 'Exchange',
    merchant_name: null,
    merchant_logo: null,
    status: 'completed',
    reference: 'EX-001',
    recipient_id: null,
    created_at: daysAgo(12, 15, 0),
  },
];

export const seedSetupProgress: SetupProgress = {
  id: 'setup-001',
  user_id: USER_ID,
  step_add_money: true,
  step_order_card: false,
  step_set_pin: false,
  step_verify_identity: true,
  step_enable_notifications: false,
  completed: false,
  created_at: daysAgo(90),
  updated_at: daysAgo(0),
};

export interface WatchlistItemWithPrice extends WatchlistItem {
  price: number;
  change24h: number;
  sparkline: number[];
}

export const seedWatchlist: WatchlistItemWithPrice[] = [
  {
    id: 'watch-001',
    user_id: USER_ID,
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    created_at: daysAgo(30),
    price: 67432.50,
    change24h: 2.34,
    sparkline: [65000, 65500, 66000, 65800, 66500, 67000, 67432],
  },
  {
    id: 'watch-002',
    user_id: USER_ID,
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    created_at: daysAgo(30),
    price: 3521.80,
    change24h: -1.12,
    sparkline: [3600, 3580, 3550, 3530, 3500, 3510, 3521],
  },
  {
    id: 'watch-003',
    user_id: USER_ID,
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    type: 'commodity',
    created_at: daysAgo(30),
    price: 1.0842,
    change24h: 0.15,
    sparkline: [1.08, 1.081, 1.082, 1.083, 1.082, 1.084, 1.0842],
  },
];

export const spendingByCategory = [
  { category: 'Food & Drink', amount: 9819, color: '#FF6B6B' },
  { category: 'Transport', amount: 3890, color: '#4ECDC4' },
  { category: 'Shopping', amount: 19877, color: '#45B7D1' },
  { category: 'Entertainment', amount: 4097, color: '#96CEB4' },
];
